version: '3.8'

services:
  # Banco de dados MariaDB
  mariadb:
    image: mariadb:10.11
    container_name: sotero-mariadb-dev
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_dev_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - sotero-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # Backend NestJS em modo desenvolvimento
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sotero-backend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - sotero-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  mariadb_dev_data:
    driver: local

networks:
  sotero-network:
    driver: bridge
